service: peacelife-contact-lambda

plugins:
  - serverless-prune-plugin

custom:
  prune:
    automatic: true
    number: 10

functions:
  peacelifeContactLambda:
    handler: com.peacelife.PeaceLifeLambdaEntryClass
    events:
      - httpApi:
          path: /contact
          method: post

    environment:
      HTTP4K_BOOTSTRAP_CLASS: com.peacelife.PeaceLifeLambda
      EVENT_TOPIC:
        Ref: ContactUsEmailTopic

package:
  artifact: target/PeacelifeContactLambda-1.0-SNAPSHOT.jar

provider:
  name: aws
  runtime: java17
  memorySize: 512
  timeout: 300
  httpApi:
    cors: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sns:Publish
        - sns:GetTopicAttributes
      Resource:
        - Ref: ContactUsEmailTopic
  tags:
    Name: "peacelife-contact-lambda"
  stackTags:
    Name: "peacelife-contact-lambda"
  profile: ask-user

resources:
  Resources:
    ContactUsEmailTopic:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: "Topic invoked from Contact Us lambda and sill have an email as subscriber"
